### ISSUE TITLE
@PathVariable 类型的文档有问题

### ISSUE THREAD

**Issue by Panmax** [DigAg/digag-server#5]
![image](https://user-images.githubusercontent.com/3353761/29058082-0a44b5f0-7c41-11e7-9f3d-9bdbe4c72a77.png)

如图，现在这样发送请求时(try it out!)，会把参数放在 body 中，需要在设置 `ApiImplicitParam` 时，指定 `paramType = "path"`

**Comment by Yuicon** [comment]
看的仔细  赞 :-D
